---
# tasks file for vector-role
- name: Create user/group
  tags: vector
  block:
    - name: Create vector group
      become: true
      ansible.builtin.group:
        name: vector
    - name: Create vector user
      become: true
      ansible.builtin.user:
        group: vector
        groups:
          - users
          - adm
#          - systemd-journal
        name: vector
- name: Create vector dirs
  tags: vector
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: vector
    group: vector
  loop:
    - "{{ vector_home_dir }}"
    - "{{ vector_tmp_dir }}"
    - "{{ vector_data_dir }}"
    - "{{ vector_config_dir }}"
- name: Include install Vector | apt
  ansible.builtin.include_tasks: tasks/install/apt.yml
  when: ansible_facts.pkg_mgr == "apt"
- name: Include install Vector | dnf
  ansible.builtin.include_tasks: tasks/install/dnf.yml
  when: ansible_facts.pkg_mgr == "dnf"
- name: Vector config
  tags: vector
  become: true
  ansible.builtin.template:
    backup: true
    src: "{{ vector_config_template }}"
    dest: "{{ vector_config_dir }}/vector.toml"
    group: vector
    owner: vector
    mode: "0644"
    validate: vector validate --no-environment -- %s
- name: Start Vector | directly
  tags: vector
  become: true
  ansible.builtin.shell:
    cmd: "vector --config {{ vector_config_dir }}/vector.toml &"
