---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: centos8
    image: docker.io/centos:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
